### ISSUE TITLE
Can't get initial refresh token

### ISSUE THREAD

**Issue by fr-richard** [tanaikech/OnedriveApp#7]
> Click "latest code". At First, Please Do This!
> By this click, it launches the authorization process. The refresh token was automatically saved.

I can't seem to get the initial refresh token. My refresh_token always empty initially, how to get this value from?
 @tanaikech

**Comment by tanaikech** [comment]
Thank you for your comment. When I tested my script using my library, the following result is obtained. From this result, it seems that the specification is not changed.

```json
{
  "token_type": "Bearer",
  "scope": "###",
  "expires_in": 3600,
  "ext_expires_in": 3600,
  "access_token": "###",
  "refresh_token": "###"
}
```

Unfortunately, I couldn't replicate your following situation.

> I can't seem to get the initial refresh token. My refresh_token always empty initially, how to get this value from?

But, I would like to support you. When I could correctly replicate your situation, I would like to think of a solution. I apologize that I cannot replicate your current issue in my test.

**Comment by fr-richard** [comment]
Good lord, sorry I was using `secret-id`, instead of `secret-value`!! Sorry for the confusion, now it works flawlessly!! Amazing tool @tanaikech !!!

For those who did the same mistake with mine, you will stuck in this blue screen.. Check your client secret value/client id 😄 
![Screen Shot 2023-03-27 at 13 43 50](https://user-images.githubusercontent.com/95075507/227853447-2e6b2967-adb8-4071-af56-cf9a010723db.png)
