### ISSUE TITLE
Can't use Send Mail 

### ISSUE THREAD

**Issue by XuanBao97** [tanaikech/OnedriveApp#9]
I have a question:
After finished  Access token and refresh token , step 4 . Do i need to run the doGet Function on Appscript ?
I haven't run doGet Function on Appscript yet and try to run below Function and it logged "undefined" and checked my email but no new mail. 
Can u help me. Tks!!
![Question](https://github.com/tanaikech/OnedriveApp/assets/66349467/3d4befcd-ce16-44f4-b09f-9aa787c31f99)

**Comment by XuanBao97** [comment]
This is log afer ran doGet Function
![doGet1](https://github.com/tanaikech/OnedriveApp/assets/66349467/a8fff5e1-236c-4e65-a856-35523a3f2168)

**Comment by tanaikech** [comment]
Thank you for your comment. Unfortunately, it seems that in the current stage, when an email is sent with the batch request, the status code `202` is returned. About `undefined`, please retrieve the access token again and test it again. By this, `202` is returned. I'm worried that the specification might have been changed on the API side. So, I would like to confirm it. When I could find it, I would like to modify the library. I deeply apologize that I cannot find it soon.

By the way, when I teste the authorize again, no error occurred. So I cannot replicate `This is log afer ran doGet Function`.

**Comment by XuanBao97** [comment]
Tks tanaikech.

**Comment by tanaikech** [comment]
When I tested other methods of "Reply Email messages" and "Forward Email messages" instead of "Send Email messages", I confirmed that no error occurred and the emails could be correctly sent. When I tested "Send Email messages", no error occurred and the email was not sent while the send email was put in the sent folder in the email. Both tests returned the status code 202. Unfortunately, I cannot still find the reason for this situation. I apologize for this. I would like to continue to look for it.

**Comment by XuanBao97** [comment]
> When I tested other methods of "Reply Email messages" and "Forward Email messages" instead of "Send Email messages", I confirmed that no error occurred and the emails could be correctly sent. When I tested "Send Email messages", no error occurred and the email was not sent while the send email was put in the sent folder in the email. Both tests returned the status code 202. Unfortunately, I cannot still find the reason for this situation. I apologize for this. I would like to continue to look for it.

sorry my fault. ,my microsoft acc doesn't have permission, now it works perfect , tks.

**Comment by tanaikech** [comment]
Thank you for replying. I understood about permission.
